### ISSUE TITLE
長條圖5-9歲排錯位子

### ISSUE THREAD

**Issue by antarestrue** [kiang/covid19#10]
是個很小的問題  如圖

![image](https://user-images.githubusercontent.com/4499366/120147603-7a7e4a80-c219-11eb-9456-9517132797a8.png)

**Comment by kiang** [comment]
感謝回報，已經修正
https://github.com/kiang/od.cdc.gov.tw/commit/ff297485d358c3110432a38bd522536fe8c99d74
