### ISSUE TITLE
有個Bug

### ISSUE THREAD

**Issue by fizzytsai** [kiang/covid19#12]
「累積數」是對的，但「增加率」是錯的。而且不是全錯，是部分天數或部分地區有錯。

**Comment by kiang** [comment]
有修過一些，可以試試強制重新整理瀏覽器，如果還有看到錯誤可以直接提供截圖或是行政區

**Comment by kiang** [comment]
找到一個程式上的邏輯錯誤，修正後已經更新舊有資料，可以再試試
https://github.com/kiang/od.cdc.gov.tw/commit/afa0dde3fe2701c096c33a844ca9128896ff6244
