### ISSUE TITLE
縣市病例地圖無資料時不會歸零

### ISSUE THREAD

**Issue by Jeremy-VVu** [kiang/covid19#16]
https://kiang.github.io/covid19/city/
選擇前後日，若該日無資料，地圖顏色及數值不會歸零、會卡在前一筆有資料的資訊。

![image](https://user-images.githubusercontent.com/59771521/121224737-727a7680-c8bb-11eb-9af3-889f7e829aa3.png)

**Comment by kiang** [comment]
累積數本來就不會歸零的？

**Comment by kiang** [comment]
不過增加率的確有提到的問題，目前嘗試修正中

**Comment by Jeremy-VVu** [comment]
累計數也有問題
3/31 苗栗累計確診307人
如果前一日沒有資料，讓它變成灰色~顯示無資料呢?
![image](https://user-images.githubusercontent.com/59771521/121226355-0ac52b00-c8bd-11eb-97cc-7687ca5bed6a.png)

**Comment by kiang** [comment]
已經修正，感謝
6c094b590ba2d4711e198bca8161a59844fccb4b

在鄉鎮市區版本有修正過，當時忘記把調整的部份套用到縣市版本
