### ISSUE TITLE
資料history日期可以更往前一點嗎？

### ISSUE THREAD

**Issue by GabrielGer** [kiang/covid19#17]
謝謝您辛苦做這個網站，這對我這一陣子觀察周邊疫情發展情況很有幫助。
但有個問題是，因為資料history的關係，我曾經一度搞不清楚到底確診數量怎麼算出來的。
直到我自己找到國網的網站才搞清楚(事實上疾管署的網站沒有每天的案例數字)。
鑑於貴網站已經是最普及的民眾前端資料來源，建議資料的history可以再往前一點，
可能給到5/10（因為5/11開始有病例），給您參考，感謝！一起加油！

![FireShot Capture 032 - 台灣 Covid-19 本土病例地圖 - kiang github io](https://user-images.githubusercontent.com/85594772/121278412-1b00f880-c905-11eb-917c-743a0baa869c.png)

**Comment by kiang** [comment]
好的，已經把顯示的天數從 20 天改為 40 天，主要是怕顯示太多資料畫面變得擁擠
cc0ea5fc8109275bcef3ada17499f145b9b31a72
