### ISSUE TITLE
建議台灣 Covid-19 本土病例地圖上可否增加各縣市的死亡人數與死亡率資料，感謝您

### ISSUE THREAD

**Issue by jason168a** [kiang/covid19#18]
建議台灣 Covid-19 本土病例地圖上可否增加各縣市的死亡人數與死亡率資料，感謝您

**Comment by kiang** [comment]
目前相關統計都只有全國總數，要有資料來源才有辦法處理

**Comment by jason168a** [comment]
非常感謝您來信告知，請問你是否知道各縣市的死亡人數可以從哪裡取得呢？




kiang ***@***.***> 於 2021年6月10日 週四 上午11:28寫道：

**Comment by kiang** [comment]
目前並不清楚
