### ISSUE TITLE
建議可以有一個單日或7日平均地圖

### ISSUE THREAD

**Issue by antarestrue** [kiang/covid19#19]
目前地圖只能選累積數跟增加率。但到現在已過了一個月，有些地方疫情退燒，光從累積數看不出來。看增加率又只能知道增減而不能知道目前疫情程度。
現在雖然也可以看7日平均跟每日確診數，但要一個一個行政區點開，無法看到全局。

**Comment by kiang** [comment]
![Screenshot from 2021-06-13 10-42-22](https://user-images.githubusercontent.com/47844/121793923-65041a00-cc36-11eb-959e-f27456a90052.png)
加入了 7日平均 功能，可以試試

**Comment by antarestrue** [comment]
感謝!
