### ISSUE TITLE
每日確診人數無資料

### ISSUE THREAD

**Issue by Jeremy-VVu** [kiang/covid19#21]
之前這邊有每日確診人數，但現在卻沒有了
![image](https://user-images.githubusercontent.com/59771521/122180901-6f831580-cebb-11eb-9e8b-61de12156775.png)

**Comment by kiang** [comment]
因為原始資料調整格式，已經修正，大概等個 1-2 分鐘就可以恢復
https://github.com/kiang/od.cdc.gov.tw/commit/c390a2f596e1623c417e5e04d2208966dac3b801
