### ISSUE TITLE
今天的數字

### ISSUE THREAD

**Issue by davidlin11** [kiang/covid19#22]
今天的數字有誤吧？嚇死人了！

**Comment by kiang** [comment]
原始資料問題，可以參考
https://facebook.com/282921805214623/posts/1846205325552922/

**Comment by davidlin11** [comment]
了解，感謝。

**Comment by kiang** [comment]
數字已經修正
https://github.com/kiang/od.cdc.gov.tw/commit/01979403968a1b5a79230533db46d9e3fe0c2520
