### ISSUE TITLE
宜蘭縣數字差 1

### ISSUE THREAD

**Issue by kiang** [kiang/covid19#23]
![ilan](https://user-images.githubusercontent.com/47844/123215090-97e1c400-d4fa-11eb-94a4-3f4c61743380.jpg)

6/23 的統計數字，宜蘭縣政府衛生局數字為 95 例
https://www.ilshb.gov.tw/index.php?catid=14&fieldid=24&cid=147&id=1822&action=view

但疾管署數字加總後是 96 例

**Comment by GG9k** [comment]
可能是這個案例造成的？

6/21 https://www.facebook.com/ilshb/posts/6006442989431133
『 宜蘭今(21)日無新增個案，全縣確診總案數調降1例。縣長林姿妙表示，昨(20)日公布的個案，由於實際居住地不在宜蘭，依中央流行疫情指揮中心規定，將移至實際居住地所轄管理，宜蘭的總案數從94案調降為93案。另外，為了保障市場第一線管理人員的健康，縣府已於6月18日建請中央列入疫苗優先施打對象，以維護執勤人員的生命安全。』

![131382399_6006442616097837_1486359170764026426_n](https://user-images.githubusercontent.com/86453833/123367089-f155fb80-d5ab-11eb-81ca-0caba4d3f46e.jpg)

**Comment by kiang** [comment]
疾管署的資料是會回頭修正的，如果順利移轉會反映在數字上，只是沒有其他開放資料能夠進一步驗證，只能記錄民眾提到的疑問

**Comment by kiang** [comment]
民眾回報已經修正
https://github.com/kiang/od.cdc.gov.tw/commit/1738875fc14b1e87e25fda007d208ffbe23ac985
