### ISSUE TITLE
確診後已經可以出院解除隔離、確診14天後已經過世

### ISSUE THREAD

**Issue by Donyush** [kiang/covid19#26]
希望能夠加入「確診後已經可以出院解除隔離」、「確診14天後已經過世」的消去選項⋯⋯

不過這是民間自發的統計顯示，其實這是認真的地方政府應該做的事情

也不好意思要求人家做那麼多

**Comment by kiang** [comment]
主要是沒有完整的資料可以配對，政府端釋出資料才能進行吧

**Comment by Donyush** [comment]
辛苦您們了！

盡量督促台北市政府和CDC

**Comment by kiang** [comment]
指揮中心統計，截至目前國內累計1,532,252例新型冠狀病毒肺炎相關通報(含1,515,985例排除)，其中15,128例確診，分別為1,190例境外移入，13,885例本土病例，36例敦睦艦隊、2例航空器感染、1例不明及14例調查中；無新增空號病例，累計105例移除為空號。自2020年起累計累計715例COVID-19死亡病例，其中707例本土，個案居住縣市分布為新北市361例、臺北市271例、基隆市24例、桃園市20例、彰化縣12例、新竹縣7例、臺中市4例、宜蘭縣及花蓮縣各2例，苗栗縣、臺東縣、雲林縣及高雄市各1例；另8例為境外移入。

https://www.cdc.gov.tw/Bulletin/Detail/2Rt1n0uftGTcpzceVxt5Zg?typeid=9
