### ISSUE TITLE
Default location should be forced to be in Taiwan when device location is outside Taiwan

### ISSUE THREAD

**Issue by jlick** [kiang/covid19#31]
I live in Taipei, Zhongshan District but am currently outside of Taiwan. I had enabled "allow location access" in my browser. After I left Taiwan when accessing the site I saw only a white screen. This was because it was showing my current location, but only Taiwan locations are supported, so no data is shown when outside Taiwan. I had to use zoom and scroll for a long time to find Taiwan. 

Suggested fix: Code should detect when a device location is outside the general Taiwan area and instead use a default location inside Taiwan or the last location accessed instead of showing a white screen.

Workaround: I disabled "allow location access" for the site. With location disabled, the site defaults to Tainan and I can find Taipei quickly enough.

**Comment by kiang** [comment]
![Screenshot from 2021-08-09 16-14-23](https://user-images.githubusercontent.com/47844/128677060-b6c1b54d-1fcf-4d27-be7e-a32c122e035a.png)

Just add a quick fix to help you move back to Taiwan by clicking the new button.

**Comment by jlick** [comment]
Thank you! That works!
