### ISSUE TITLE
顏色不正確

### ISSUE THREAD

**Issue by ghost** [kiang/covid19#37]
人數和顏色，不是很正確，如：佳里94人、麻豆區92，應該是深紅色....

**Comment by kiang** [comment]
配色是依據每萬人確診率，麻豆 >20 所以是另外一個區間，可以參考右手邊說明的圖例

![Screenshot from 2022-05-07 22-29-02](https://user-images.githubusercontent.com/47844/167258609-51e01d62-4e7a-48a3-9219-4a5e9a8b6049.png)

**Comment by ghost** [comment]
了解，已經發現了，但不知怎麼刪掉此問題！
