### ISSUE TITLE
建議新增功能

### ISSUE THREAD

**Issue by Jialiangni** [kiang/covid19#4]
點選地區的時候可以show出
1.  每天確診數的曲線圖 
2. 過去七天確診數平均數的曲線圖

**Comment by kiang** [comment]
範圍縮小到鄉鎮市區時每日曲線變化容易忽起忽落，所以改用長條圖呈現每日確診數，同時加入性別、年齡的圓餅圖

**Comment by Jialiangni** [comment]
建議年齡也用圓餅圖顯示  可以更清楚提醒該地區高危險群

**Comment by kiang** [comment]
![Screenshot_20210529-235850](https://user-images.githubusercontent.com/47844/120076771-de015e80-c0d9-11eb-9a96-19f93d87dd06.png)

年齡是圓餅圖沒錯，可以試試

**Comment by Jialiangni** [comment]
說錯了 建議用bar chart 長條圖比較容易看得出來高風險族群

**Comment by kiang** [comment]
已經調整
6a2b2b13ed918468286f43ff653aa1c119179d92
